# Generated by Django 4.2.4 on 2023-08-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Received', max_length=50),
        ),
    ]
